# Generated by Django 5.1.4 on 2026-04-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SharedMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("role", models.CharField(default="member", max_length=30)),
                ("platform_roles", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "org_members",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SharedOrganization",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True)),
                ("active_products", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SharedSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.UUIDField()),
                ("plan_id", models.IntegerField(blank=True, null=True)),
                ("amplex_users", models.IntegerField(default=0)),
                ("nexus_users", models.IntegerField(default=0)),
                ("nexus_channels", models.IntegerField(default=0)),
                (
                    "entity_credit_tier",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("entity_credits", models.IntegerField(default=0)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "final_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SharedUser",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("roles", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AmplexOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub_org_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.CharField(
                        db_index=True, default="", max_length=100, unique=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "amplex_organizations",
            },
        ),
        migrations.CreateModel(
            name="AmplexUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub_id",
                    models.CharField(
                        db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ("login", models.CharField(db_index=True, max_length=255, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("is_internal", models.BooleanField(default=True)),
                ("permissions", models.JSONField(blank=True, null=True)),
                ("hub_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "amplex_users",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                ("mobile", models.CharField(blank=True, max_length=64, null=True)),
                ("is_company", models.BooleanField(default=False)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("street2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
                ("state_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("vat", models.CharField(blank=True, max_length=32, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("hub_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="api.amplexorganization",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_contacts",
            },
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("field_type", models.CharField(default="text", max_length=16)),
                ("options", models.TextField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=10)),
                ("active", models.BooleanField(default=True)),
                ("required", models.BooleanField(default=False)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="api.amplexorganization",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_custom_fields",
                "unique_together": {("org", "name")},
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_type", models.CharField(default="note", max_length=32)),
                ("body", models.TextField(blank=True, null=True)),
                ("preview", models.CharField(blank=True, max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.amplexuser",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_interactions",
            },
        ),
        migrations.CreateModel(
            name="InteractionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("storage_path", models.CharField(max_length=1024)),
                ("file_size", models.IntegerField(default=0)),
                ("mimetype", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="api.interaction",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_interaction_files",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(default="opportunity", max_length=16)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_from",
                    models.EmailField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("mobile", models.CharField(blank=True, max_length=64, null=True)),
                ("expected_revenue", models.FloatField(default=0)),
                ("probability", models.FloatField(default=0)),
                ("priority", models.CharField(default="0", max_length=4)),
                ("description", models.TextField(blank=True, null=True)),
                ("function", models.CharField(blank=True, max_length=128, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
                ("state_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("date_deadline", models.DateField(blank=True, null=True)),
                ("date_closed", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="api.contact",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="api.amplexorganization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="api.amplexuser",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_leads",
            },
        ),
        migrations.AddField(
            model_name="interaction",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="api.lead",
            ),
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("field_type", models.CharField(default="text", max_length=16)),
                ("value", models.TextField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=10)),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="api.customfield",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="api.lead",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_custom_field_values",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(default="todo", max_length=32)),
                ("summary", models.CharField(blank=True, max_length=512, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "date_deadline",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="api.amplexuser",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.lead",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_activities",
            },
        ),
        migrations.CreateModel(
            name="LeadAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("storage_path", models.CharField(max_length=1024)),
                ("file_size", models.IntegerField(default=0)),
                ("mimetype", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.lead",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_lead_attachments",
            },
        ),
        migrations.CreateModel(
            name="LostReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_reasons",
                        to="api.amplexorganization",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_lost_reasons",
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="lost_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.lostreason",
            ),
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="api.amplexorganization",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_sources",
                "unique_together": {("org", "name")},
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.source",
            ),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("sequence", models.IntegerField(default=10)),
                ("is_won", models.BooleanField(default=False)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="api.amplexorganization",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_stages",
                "ordering": ["sequence"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="api.stage",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("color", models.IntegerField(default=0)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="api.amplexorganization",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_tags",
                "unique_together": {("org", "name")},
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="leads", to="api.tag"
            ),
        ),
        migrations.CreateModel(
            name="AmplexOrgMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="member", max_length=32)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="api.amplexorganization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.amplexuser",
                    ),
                ),
            ],
            options={
                "db_table": "amplex_org_members",
                "unique_together": {("org", "user")},
            },
        ),
    ]
