# Generated by Django 5.1.15 on 2026-05-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="SharedMembership"),
                migrations.DeleteModel(name="SharedOrganization"),
                migrations.DeleteModel(name="SharedSubscription"),
                migrations.DeleteModel(name="SharedUser"),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name="amplexorganization",
            name="hub_org_id",
        ),
        migrations.RemoveField(
            model_name="amplexuser",
            name="hub_id",
        ),
        migrations.RemoveField(
            model_name="amplexuser",
            name="hub_synced_at",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="hub_id",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="hub_synced_at",
        ),
        migrations.AddField(
            model_name="amplexuser",
            name="password_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
