# Generated by Django 5.1.15 on 2026-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_standalone_mvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="amplexorganization",
            name="seat_limit",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="amplexuser",
            name="is_super_admin",
            field=models.BooleanField(default=False),
        ),
    ]
